"""
Alembic migration operations for database views.

Provides 7 MigrateOperation subclasses for creating, dropping, replacing,
and refreshing regular and materialized views, along with ``op.*`` helper
functions.

Usage in Alembic migrations::

    def upgrade():
        op.create_view("my_view", "SELECT id, name FROM users")
        op.create_materialized_view("mv_stats", "SELECT count(*) FROM events")

    def downgrade():
        op.drop_view("my_view")
        op.drop_materialized_view("mv_stats")
"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from alembic.operations import MigrateOperation, Operations

from sqlalchemy_utils.view import _quote_qualified_name


def _validate_definition(definition: str) -> None:
    if not isinstance(definition, str) or not definition:
        raise TypeError(
            f"definition must be a non-empty string, got {type(definition).__name__}"
        )


def _validate_name(name: str) -> None:
    if not isinstance(name, str) or not name:
        raise TypeError(
            f"name must be a non-empty string, got {type(name).__name__}"
        )


# ===================================================================
# Regular view operations
# ===================================================================


@Operations.register_operation("create_view")
class CreateViewOp(MigrateOperation):
    """Operation that emits ``CREATE [OR REPLACE] VIEW``.

    :param name: Name of the view to create.
    :param definition: SQL ``SELECT`` statement defining the view body.
    :param schema: Optional schema name; when given, the view name is
        schema-qualified in the emitted DDL.
    :param replace: Deprecated. When ``True``, emits ``CREATE OR REPLACE
        VIEW``; prefer ``op.replace_view()`` / :class:`ReplaceViewOp`
        instead, whose ``reverse()`` restores the prior definition.
    :param cascade_on_drop: When ``True`` (default), the autogenerated
        downgrade (``DROP VIEW``) uses ``CASCADE`` so dependent objects
        are removed as well.
    """

    def __init__(
        self,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        replace: bool = False,
        cascade_on_drop: bool = True,
    ) -> None:
        _validate_name(name)
        _validate_definition(definition)
        if replace:
            warnings.warn(
                "CreateViewOp(replace=True) is deprecated; use op.replace_view() "
                "or ReplaceViewOp instead. The reverse() of CreateViewOp(replace=True) "
                "emits a destructive DROP, while ReplaceViewOp.reverse() restores "
                "the prior definition.",
                DeprecationWarning,
                stacklevel=2,
            )
        self.name = name
        self.definition = definition
        self.schema = schema or None
        self.replace = replace
        self.cascade_on_drop = cascade_on_drop

    @classmethod
    def create_view(
        cls,
        operations: Operations,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        replace: bool = False,
        cascade_on_drop: bool = True,
    ) -> None:
        """Entry point for ``op.create_view()``. See class docstring for parameter details.

        Example::

            op.create_view("my_view", "SELECT id, name FROM users")
        """
        op = CreateViewOp(
            name, definition, schema=schema, replace=replace,
            cascade_on_drop=cascade_on_drop,
        )
        return operations.invoke(op)

    def reverse(self) -> DropViewOp:
        """Return the inverse: drop the view that was just created."""
        return DropViewOp(
            self.name,
            schema=self.schema,
            cascade=self.cascade_on_drop,
            definition=self.definition,
        )


@Operations.register_operation("drop_view")
class DropViewOp(MigrateOperation):
    """Operation that emits ``DROP VIEW IF EXISTS``.

    :param name: Name of the view to drop.
    :param schema: Optional schema name; when given, the view name is
        schema-qualified in the emitted DDL.
    :param cascade: When ``True`` (default), appends ``CASCADE`` to the
        ``DROP VIEW``. This corresponds to ``cascade_on_drop`` in the
        runtime DDL API (:func:`~sqlalchemy_utils.view.create_view`).
    :param definition: Optional stored definition of the view. When
        supplied, :meth:`reverse` can re-create the view for an
        autogenerated downgrade; otherwise :meth:`reverse` raises
        ``NotImplementedError``.
    """

    def __init__(
        self,
        name: str,
        *,
        schema: str | None = None,
        # Named ``cascade`` for Alembic op convention; corresponds to
        # ``cascade_on_drop`` in create_view() and ViewMixin.__view_cascade__.
        cascade: bool = True,
        definition: str | None = None,
    ) -> None:
        _validate_name(name)
        if definition is not None:
            _validate_definition(definition)
        self.name = name
        self.schema = schema or None
        self.cascade = cascade
        self.definition = definition

    @classmethod
    def drop_view(
        cls,
        operations: Operations,
        name: str,
        *,
        schema: str | None = None,
        cascade: bool = True,
        definition: str | None = None,
    ) -> None:
        """Entry point for ``op.drop_view()``. See class docstring for parameter details.

        Example::

            op.drop_view("my_view")
        """
        op = DropViewOp(
            name,
            schema=schema,
            cascade=cascade,
            definition=definition,
        )
        return operations.invoke(op)

    def reverse(self) -> CreateViewOp:
        """Return the inverse: re-create the view that was just dropped.

        Requires ``definition`` to have been stored at construction time;
        otherwise a ``NotImplementedError`` is raised because the view definition
        is unknown.
        """
        if self.definition is None:
            raise NotImplementedError(
                f"Cannot reverse DropViewOp for '{self.name}': "
                "no definition stored. Pass definition= to DropViewOp "
                "to enable automatic downgrade generation."
            )
        return CreateViewOp(
            self.name, self.definition, schema=self.schema,
            cascade_on_drop=self.cascade,
        )

@Operations.register_operation("replace_view")
class ReplaceViewOp(MigrateOperation):
    """Operation that emits ``CREATE OR REPLACE VIEW``.

    :param name: Name of the view to replace.
    :param definition: New SQL ``SELECT`` statement defining the view body.
    :param schema: Optional schema name; when given, the view name is
        schema-qualified in the emitted DDL.
    :param old_definition: Previous definition of the view. When
        supplied, :meth:`reverse` can restore the prior definition for an
        autogenerated downgrade; otherwise :meth:`reverse` raises
        ``NotImplementedError``.
    """

    def __init__(
        self,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        old_definition: str | None = None,
    ) -> None:
        _validate_name(name)
        _validate_definition(definition)
        self.name = name
        self.definition = definition
        self.schema = schema or None
        self.old_definition = old_definition

    @classmethod
    def replace_view(
        cls,
        operations: Operations,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        old_definition: str | None = None,
    ) -> None:
        """Entry point for ``op.replace_view()``. See class docstring for parameter details.

        Example::

            op.replace_view(
                "my_view",
                "SELECT id, name, email FROM users",
                old_definition="SELECT id, name FROM users",
            )
        """
        op = ReplaceViewOp(
            name, definition, schema=schema, old_definition=old_definition
        )
        return operations.invoke(op)

    def reverse(self) -> ReplaceViewOp:
        """Return the inverse: replace back to the old definition.

        Requires ``old_definition``; otherwise raises ``NotImplementedError``.
        """
        if self.old_definition is None:
            raise NotImplementedError(
                f"Cannot reverse ReplaceViewOp for '{self.name}': "
                "no old_definition stored. Pass old_definition= to "
                "ReplaceViewOp to enable automatic downgrade generation."
            )
        return ReplaceViewOp(
            self.name, self.old_definition, schema=self.schema,
            old_definition=self.definition,
        )


# ===================================================================
# Materialized view operations
# ===================================================================


@Operations.register_operation("create_materialized_view")
class CreateMaterializedViewOp(MigrateOperation):
    """Operation that emits ``CREATE MATERIALIZED VIEW``.

    :param name: Name of the materialized view to create.
    :param definition: SQL ``SELECT`` statement defining the materialized
        view body.
    :param schema: Optional schema name; when given, the view name is
        schema-qualified in the emitted DDL.
    :param with_data: When ``True``, emits ``WITH DATA`` (populates the
        materialized view immediately). When ``False`` (default), emits
        ``WITH NO DATA`` (creates the MV empty).
    :param cascade_on_drop: When ``True`` (default), the autogenerated
        downgrade (``DROP MATERIALIZED VIEW``) uses ``CASCADE`` so
        dependent objects are removed as well.

    .. note:: Materialized views are PostgreSQL-specific; other dialects
       will raise at execute time.

    .. note::
       Autogenerate always emits ``with_data=False`` (unpopulated MVs);
       manual ``op.create_materialized_view()`` also defaults to
       ``WITH NO DATA`` for consistency.
    """

    def __init__(
        self,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        with_data: bool = False,
        cascade_on_drop: bool = True,
    ) -> None:
        _validate_name(name)
        _validate_definition(definition)
        self.name = name
        self.definition = definition
        self.schema = schema or None
        self.with_data = with_data
        self.cascade_on_drop = cascade_on_drop

    @classmethod
    def create_materialized_view(
        cls,
        operations: Operations,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        with_data: bool = False,
        cascade_on_drop: bool = True,
    ) -> None:
        """Entry point for ``op.create_materialized_view()``. See class docstring for parameter details.

        Example::

            op.create_materialized_view(
                "mv_stats", "SELECT count(*) FROM events"
            )
        """
        op = CreateMaterializedViewOp(
            name, definition, schema=schema, with_data=with_data,
            cascade_on_drop=cascade_on_drop,
        )
        return operations.invoke(op)

    def reverse(self) -> DropMaterializedViewOp:
        """Return the inverse: drop the materialized view just created."""
        return DropMaterializedViewOp(
            self.name,
            schema=self.schema,
            cascade=self.cascade_on_drop,
            definition=self.definition,
            with_data=self.with_data,
        )

@Operations.register_operation("drop_materialized_view")
class DropMaterializedViewOp(MigrateOperation):
    """Operation that emits ``DROP MATERIALIZED VIEW IF EXISTS``.

    :param name: Name of the materialized view to drop.
    :param schema: Optional schema name; when given, the view name is
        schema-qualified in the emitted DDL.
    :param cascade: When ``True`` (default), appends ``CASCADE`` to the
        ``DROP MATERIALIZED VIEW``. This corresponds to
        ``cascade_on_drop`` in the runtime DDL API
        (:func:`~sqlalchemy_utils.view.create_materialized_view`).
    :param definition: Optional stored definition of the materialized
        view. When supplied, :meth:`reverse` can re-create the MV for an
        autogenerated downgrade; otherwise :meth:`reverse` raises
        ``NotImplementedError``.
    :param with_data: Carried solely so :meth:`reverse` can restore the
        materialized view with the original ``WITH DATA`` / ``WITH NO
        DATA`` clause; the ``DROP`` itself ignores it.

    .. note:: Materialized views are PostgreSQL-specific; other dialects
       will raise at execute time.
    """

    def __init__(
        self,
        name: str,
        *,
        schema: str | None = None,
        # Named ``cascade`` for Alembic op convention; corresponds to
        # ``cascade_on_drop`` in create_view() and ViewMixin.__view_cascade__.
        cascade: bool = True,
        definition: str | None = None,
        with_data: bool = False,
    ) -> None:
        _validate_name(name)
        if definition is not None:
            _validate_definition(definition)
        self.name = name
        self.schema = schema or None
        self.cascade = cascade
        self.definition = definition
        self.with_data = with_data

    @classmethod
    def drop_materialized_view(
        cls,
        operations: Operations,
        name: str,
        *,
        schema: str | None = None,
        cascade: bool = True,
        definition: str | None = None,
        with_data: bool = False,
    ) -> None:
        """Entry point for ``op.drop_materialized_view()``. See class docstring for parameter details.

        Example::

            op.drop_materialized_view("mv_stats")
        """
        op = DropMaterializedViewOp(
            name, schema=schema, cascade=cascade, definition=definition,
            with_data=with_data,
        )
        return operations.invoke(op)

    def reverse(self) -> CreateMaterializedViewOp:
        """Return the inverse: re-create the materialized view.

        Requires ``definition``; otherwise raises ``NotImplementedError``.
        """
        if self.definition is None:
            raise NotImplementedError(
                f"Cannot reverse DropMaterializedViewOp for '{self.name}': "
                "no definition stored. Pass definition= to "
                "DropMaterializedViewOp to enable automatic downgrade "
                "generation."
            )
        return CreateMaterializedViewOp(
            self.name, self.definition, schema=self.schema,
            with_data=self.with_data,
            cascade_on_drop=self.cascade,
        )

@Operations.register_operation("replace_materialized_view")
class ReplaceMaterializedViewOp(MigrateOperation):
    """Operation that drops and re-creates a materialized view.

    PostgreSQL does not support ``CREATE OR REPLACE MATERIALIZED VIEW``
    so this operation issues a ``DROP`` followed by a ``CREATE``.

    :param name: Name of the materialized view to replace.
    :param definition: New SQL ``SELECT`` statement defining the
        materialized view body.
    :param schema: Optional schema name; when given, the view name is
        schema-qualified in the emitted DDL.
    :param with_data: When ``True``, emits ``WITH DATA`` (populates the
        materialized view immediately). When ``False`` (default), emits
        ``WITH NO DATA`` (creates the MV empty).
    :param cascade: When ``True`` (default), appends ``CASCADE`` to the
        ``DROP MATERIALIZED VIEW``.
    :param old_definition: Previous definition of the materialized view.
        When supplied, :meth:`reverse` can restore the prior definition
        for an autogenerated downgrade; otherwise :meth:`reverse` raises
        ``NotImplementedError``.

    .. note:: Materialized views are PostgreSQL-specific; other dialects
       will raise at execute time.

    .. note::
       Autogenerate always emits ``with_data=False`` (unpopulated MVs);
       manual ``op.replace_materialized_view()`` also defaults to
       ``WITH NO DATA`` for consistency.
    """

    def __init__(
        self,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        with_data: bool = False,
        cascade: bool = True,
        old_definition: str | None = None,
    ) -> None:
        _validate_name(name)
        _validate_definition(definition)
        self.name = name
        self.definition = definition
        self.schema = schema or None
        self.with_data = with_data
        self.cascade = cascade
        self.old_definition = old_definition
    @classmethod
    def replace_materialized_view(
        cls,
        operations: Operations,
        name: str,
        definition: str,
        *,
        schema: str | None = None,
        with_data: bool = False,
        cascade: bool = True,
        old_definition: str | None = None,
    ) -> None:
        """Entry point for ``op.replace_materialized_view()``. See class docstring for parameter details.

        Example::

            op.replace_materialized_view(
                "mv_stats",
                "SELECT count(*), max(ts) FROM events",
                old_definition="SELECT count(*) FROM events",
            )
        """
        op = ReplaceMaterializedViewOp(
            name,
            definition,
            schema=schema,
            with_data=with_data,
            cascade=cascade,
            old_definition=old_definition,
        )
        return operations.invoke(op)

    def reverse(self) -> ReplaceMaterializedViewOp:
        """Return the inverse: replace back to old definition.

        Requires ``old_definition``; otherwise raises ``NotImplementedError``.
        """
        if self.old_definition is None:
            raise NotImplementedError(
                f"Cannot reverse ReplaceMaterializedViewOp for "
                f"'{self.name}': no old_definition stored. Pass "
                "old_definition= to ReplaceMaterializedViewOp to enable "
                "automatic downgrade generation."
            )
        return ReplaceMaterializedViewOp(
            self.name,
            self.old_definition,
            schema=self.schema,
            with_data=self.with_data,
            cascade=self.cascade,
            old_definition=self.definition,
        )

# ===================================================================
# Refresh materialized view operation
# ===================================================================


@Operations.register_operation("refresh_materialized_view")
class RefreshMaterializedViewOp(MigrateOperation):
    """Operation that emits ``REFRESH MATERIALIZED VIEW``.

    :param name: Name of the materialized view to refresh.
    :param schema: Optional schema name; when given, the view name is
        schema-qualified in the emitted DDL.
    :param concurrently: When ``True``, emits ``REFRESH MATERIALIZED
        VIEW CONCURRENTLY`` (non-blocking refresh; requires a unique
        index on the MV). When ``False`` (default), emits a plain
        ``REFRESH MATERIALIZED VIEW``.

    .. note:: Materialized views are PostgreSQL-specific; other dialects
       will raise at execute time.
    """

    def __init__(
        self,
        name: str,
        *,
        schema: str | None = None,
        concurrently: bool = False,
    ) -> None:
        _validate_name(name)
        self.name = name
        self.schema = schema or None
        self.concurrently = concurrently

    @classmethod
    def refresh_materialized_view(
        cls,
        operations: Operations,
        name: str,
        *,
        schema: str | None = None,
        concurrently: bool = False,
    ) -> None:
        """Entry point for ``op.refresh_materialized_view()``. See class docstring for parameter details.

        Example::

            op.refresh_materialized_view("mv_stats")
        """
        op = cls(name, schema=schema, concurrently=concurrently)
        return operations.invoke(op)

    def reverse(self) -> "RefreshMaterializedViewOp":
        """REFRESH MATERIALIZED VIEW is not meaningfully reversible.

        You cannot "un-refresh" a materialized view, so reverse()
        refuses rather than silently emit another REFRESH in the
        downgrade. Implement the downgrade step manually if needed.
        """
        raise NotImplementedError(
            "REFRESH MATERIALIZED VIEW is not meaningfully reversible; "
            "remove it from downgrade() or implement manually."
        )

# ===================================================================
# SQL implementations
# ===================================================================


@Operations.implementation_for(CreateViewOp)
def _create_view_impl(operations: Operations, op: CreateViewOp) -> None:
    """Execute ``CREATE [OR REPLACE] VIEW`` via the migration connection."""
    if op.replace:
        return _replace_view_impl(operations, op)
    dialect = operations.get_bind().dialect
    qualified = _quote_qualified_name(dialect, op.name, op.schema)
    sql = f"CREATE VIEW {qualified} AS {op.definition}"
    operations.execute(sa.text(sql))


@Operations.implementation_for(DropViewOp)
def _drop_view_impl(operations: Operations, op: DropViewOp) -> None:
    """Execute ``DROP VIEW IF EXISTS`` via the migration connection."""
    dialect = operations.get_bind().dialect
    qualified = _quote_qualified_name(dialect, op.name, op.schema)
    cascade_clause = " CASCADE" if op.cascade else ""
    sql = f"DROP VIEW IF EXISTS {qualified}{cascade_clause}"
    operations.execute(sa.text(sql))


@Operations.implementation_for(ReplaceViewOp)
def _replace_view_impl(operations: Operations, op: CreateViewOp | ReplaceViewOp) -> None:
    """Execute ``CREATE OR REPLACE VIEW`` via the migration connection."""
    dialect = operations.get_bind().dialect
    qualified = _quote_qualified_name(dialect, op.name, op.schema)
    sql = f"CREATE OR REPLACE VIEW {qualified} AS {op.definition}"
    operations.execute(sa.text(sql))


@Operations.implementation_for(CreateMaterializedViewOp)
def _create_materialized_view_impl(
    operations: Operations, op: CreateMaterializedViewOp
) -> None:
    """Execute ``CREATE MATERIALIZED VIEW … WITH [NO] DATA``."""
    dialect = operations.get_bind().dialect
    qualified = _quote_qualified_name(dialect, op.name, op.schema)
    data_clause = "WITH DATA" if op.with_data else "WITH NO DATA"
    sql = (
        f"CREATE MATERIALIZED VIEW {qualified} AS {op.definition} "
        f"{data_clause}"
    )
    operations.execute(sa.text(sql))


@Operations.implementation_for(DropMaterializedViewOp)
def _drop_materialized_view_impl(
    operations: Operations, op: DropMaterializedViewOp
) -> None:
    """Execute ``DROP MATERIALIZED VIEW IF EXISTS`` via the migration connection."""
    dialect = operations.get_bind().dialect
    qualified = _quote_qualified_name(dialect, op.name, op.schema)
    cascade_clause = " CASCADE" if op.cascade else ""
    sql = f"DROP MATERIALIZED VIEW IF EXISTS {qualified}{cascade_clause}"
    operations.execute(sa.text(sql))


@Operations.implementation_for(ReplaceMaterializedViewOp)
def _replace_materialized_view_impl(
    operations: Operations, op: ReplaceMaterializedViewOp
) -> None:
    """Drop then re-create a materialized view (PG has no OR REPLACE for MVs)."""
    dialect = operations.get_bind().dialect
    qualified = _quote_qualified_name(dialect, op.name, op.schema)
    data_clause = "WITH DATA" if op.with_data else "WITH NO DATA"

    cascade_clause = " CASCADE" if op.cascade else ""
    drop_sql = f"DROP MATERIALIZED VIEW IF EXISTS {qualified}{cascade_clause}"
    create_sql = (
        f"CREATE MATERIALIZED VIEW {qualified} AS {op.definition} "
        f"{data_clause}"
    )
    operations.execute(sa.text(drop_sql))
    operations.execute(sa.text(create_sql))


@Operations.implementation_for(RefreshMaterializedViewOp)
def _refresh_materialized_view_impl(
    operations: Operations, op: RefreshMaterializedViewOp
) -> None:
    """Execute ``REFRESH MATERIALIZED VIEW`` via the migration connection."""
    dialect = operations.get_bind().dialect
    qualified = _quote_qualified_name(dialect, op.name, op.schema)
    concurrently = "CONCURRENTLY " if op.concurrently else ""
    sql = f"REFRESH MATERIALIZED VIEW {concurrently}{qualified}"
    operations.execute(sa.text(sql))
