"""
Alembic autogenerate renderers for view migration operations.

Registers 7 renderer functions with ``alembic.autogenerate.renderers.dispatch_for``
so that Alembic's autogenerate can render view operations as Python code strings
in migration scripts.
"""

from __future__ import annotations

from alembic.autogenerate import renderers
from alembic.autogenerate.api import AutogenContext

from sqlalchemy_utils.alembic.operations import (
    CreateViewOp,
    DropViewOp,
    ReplaceViewOp,
    CreateMaterializedViewOp,
    DropMaterializedViewOp,
    ReplaceMaterializedViewOp,
    RefreshMaterializedViewOp,
)


def _schema_part(op) -> str:
    """Render the ``schema=`` kwarg fragment when ``op.schema`` is set."""
    return f", schema={op.schema!r}" if op.schema is not None else ""


def _cascade_part(op) -> str:
    """Render the ``cascade=False`` kwarg fragment when cascade is disabled."""
    return "" if op.cascade else ", cascade=False"


def _cascade_on_drop_part(op) -> str:
    """Render the ``cascade_on_drop=False`` kwarg fragment when disabled.

    Mirrors :func:`_cascade_part` for the ``cascade_on_drop`` field carried
    by ``CreateViewOp`` / ``CreateMaterializedViewOp`` so the autogenerated
    downgrade (reverse → drop op) honors the non-cascading drop instead of
    defaulting to ``CASCADE``.
    """
    return "" if op.cascade_on_drop else ", cascade_on_drop=False"


def _with_data_part(op) -> str:
    """Render the ``with_data=True`` kwarg fragment when with_data is enabled."""
    return "" if not op.with_data else ", with_data=True"


def _definition_part(op) -> str:
    """Render the ``definition=`` kwarg fragment when ``op.definition`` is set."""
    return f", definition={op.definition!r}" if op.definition is not None else ""


def _old_def_part(op) -> str:
    """Render the ``old_definition=`` kwarg fragment when ``op.old_definition`` is set."""
    return (
        f", old_definition={op.old_definition!r}"
        if op.old_definition is not None
        else ""
    )


@renderers.dispatch_for(CreateViewOp)
def render_create_view(autogen_context: AutogenContext, op: CreateViewOp) -> str:
    """Render a CreateViewOp as op.create_view(...) code."""
    return (
        f"op.create_view({op.name!r}, {op.definition!r}{_schema_part(op)}"
        f"{_cascade_on_drop_part(op)})"
    )


@renderers.dispatch_for(DropViewOp)
def render_drop_view(autogen_context: AutogenContext, op: DropViewOp) -> str:
    """Render a DropViewOp as op.drop_view(...) code."""
    return (
        f"op.drop_view({op.name!r}{_schema_part(op)}"
        f"{_cascade_part(op)}{_definition_part(op)})"
    )


@renderers.dispatch_for(ReplaceViewOp)
def render_replace_view(autogen_context: AutogenContext, op: ReplaceViewOp) -> str:
    """Render a ReplaceViewOp as op.replace_view(...) code."""
    return (
        f"op.replace_view({op.name!r}, {op.definition!r}"
        f"{_schema_part(op)}{_cascade_part(op)}{_old_def_part(op)})"
    )


@renderers.dispatch_for(CreateMaterializedViewOp)
def render_create_materialized_view(
    autogen_context: AutogenContext, op: CreateMaterializedViewOp
) -> str:
    """Render a CreateMaterializedViewOp as op.create_materialized_view(...) code."""
    return (
        f"op.create_materialized_view({op.name!r}, {op.definition!r}"
        f"{_schema_part(op)}{_with_data_part(op)}{_cascade_on_drop_part(op)})"
    )


@renderers.dispatch_for(DropMaterializedViewOp)
def render_drop_materialized_view(
    autogen_context: AutogenContext, op: DropMaterializedViewOp
) -> str:
    """Render a DropMaterializedViewOp as op.drop_materialized_view(...) code.

    ``with_data`` is rendered even though ``DROP MATERIALIZED VIEW`` ignores
    it: it is carried on the op so the autogenerated downgrade (which
    re-creates the MV via :meth:`DropMaterializedViewOp.reverse`) preserves
    the original ``WITH DATA`` / ``WITH NO DATA`` clause instead of silently
    defaulting to ``WITH NO DATA``.
    """
    return (
        f"op.drop_materialized_view({op.name!r}{_schema_part(op)}"
        f"{_cascade_part(op)}{_definition_part(op)}{_with_data_part(op)})"
    )


@renderers.dispatch_for(ReplaceMaterializedViewOp)
def render_replace_materialized_view(
    autogen_context: AutogenContext, op: ReplaceMaterializedViewOp
) -> str:
    """Render a ReplaceMaterializedViewOp as op.replace_materialized_view(...) code."""
    return (
        f"op.replace_materialized_view({op.name!r}, {op.definition!r}"
        f"{_schema_part(op)}{_with_data_part(op)}{_cascade_part(op)}"
        f"{_old_def_part(op)})"
    )


@renderers.dispatch_for(RefreshMaterializedViewOp)
def render_refresh_materialized_view(
    autogen_context: AutogenContext, op: RefreshMaterializedViewOp
) -> str:
    """Render a RefreshMaterializedViewOp as op.refresh_materialized_view(...) code."""
    concurrently_part = ", concurrently=True" if op.concurrently else ""
    return (
        f"op.refresh_materialized_view({op.name!r}"
        f"{_schema_part(op)}{concurrently_part})"
    )
